{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cb4f812d",
   "metadata": {},
   "source": [
    "# **1. About the Author**\n",
    "**Author:** Ajwa Hahsmi\\\n",
    "**Author's Contact Info:** \n",
    "- ✉️ [Email](ajwahashmi@outlook.com) \n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "af636a3f",
   "metadata": {},
   "source": [
    "# **2. About the Dataset**\n",
    "\n",
    "\n",
    "**Dataset:** Customer Shopping Behaviour Dataset\n",
    "\n",
    "\n",
    "**Data Collection Date:** October 2025\n",
    "\n",
    "\n",
    "**Dataset Source:** [Customer Data set](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbThQWWVQWElpc2lQU3BBeDJoRXV4QzFWdXlJZ3xBQ3Jtc0tsY0YyWXBGa0pzQks4cGtDaHV4OHU3bWtwS2oxQldwM1BDMzhpRUQ5b3FweEhqWGh1dDhpOGt5OWx4UF9hQlZaNmQ4Z1FEWmNWZjc2ZG1ZT1cteFVjSDk1ZVVBa0VRQkRaaWtCX0dUZFliV0YyMmI2VQ&q=https%3A%2F%2Fgithub.com%2Famlanmohanty1%2Fcustomer-trends-data-analysis-SQL-Python-PowerBI%2Fblob%2Fmain%2Fcustomer_shopping_behavior.csv&v=5PrZvPeUw60)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9bb78328",
   "metadata": {},
   "source": [
    "## 2.1 Meta Data\n",
    "\n",
    "\n",
    "This dataset contains customer data of **3500+ customers** with **18 attributes**.\n",
    "\n",
    "### Column Descriptions\n",
    "\n",
    "| Column | Description |\n",
    "|--------|-------------|\n",
    "| **Customer_ID** | Unique customer ID |\n",
    "| **Age** | Customer Age in Years |\n",
    "| **Gender** | Customer Gender Male vs Female |\n",
    "| **Item Purchased** | item purchased by customer |\n",
    "| **Category** | Main categories for items |\n",
    "| **Purchase Amount (USD)** | Amount spend on purchase item |\n",
    "| **Location** | Location state of customer in US  |\n",
    "| **Size** | Size of Item |\n",
    "| **Color** | Color of Item |\n",
    "| **Season** | Season during purchase |\n",
    "| **Review Rating** | item rating by customer |\n",
    "| **Subscription** | Subscription status |\n",
    "| **Shipping Type** | Shipping mode  |\n",
    "| **Discount applied** | Discount availed or not on item |\n",
    "| **Promo Code** | Use of promo code for discount |\n",
    "| **Previous Purchase** | How many times the previously purchased by customer |\n",
    "| **Payment Method** | Payment channel for customer |\n",
    "| **Frequency of Purchases** | Customer behaviour in Purchasing Frequency |                            |\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "08d1193f",
   "metadata": {},
   "source": [
    "# 3. **Project Overview**\n",
    "This project provides a comprehensive end-to-end data analysis solution, moving from raw data preparation to actionable business recommendations. The goal is to identify key customer segments, evaluate loyalty patterns, and determine the primary drivers behind purchase behavior.\n",
    "\n",
    "## 3.1 Objective\n",
    "\n",
    "The primary goal of this Consumer Behaviour dataset is to better understand its customers shopping behavior in order to improve the sales, customer satisfaction and long-term loyalty with data from 3500+ customers, this dataset empowers us to:\n",
    "\n",
    "- Identify and profile distinct customer segments based on demographics, purchase frequency, and channel preference\n",
    "- Determine the relative impact of discounts, product reviews, seasonality, and payment method on purchase decisions and repeat buying\n",
    "- Compare performance metrics between online and offline channels to identify strengths, gaps, and cross-channel opportunities\n",
    "- Measure customer loyalty and quantify customer lifetime value by segment\n",
    "------\n",
    "\n",
    "## 3.2 Performed Task\n",
    "\n",
    "Conduct a comprehensive Exploratory Data Analysis (EDA) on the Customer Behaviour Analysis Dataset. \n",
    "following a structured workflow:\n",
    "\n",
    "1. **Data Cleaning** → Handle missing values, duplicates, and inconsistencies\n",
    "2. **Data Wrangling** → Transform and prepare data for analysis\n",
    "3. **Exploratory Analysis** → Discover patterns and insights\n",
    "4. **Business Recommendations** → Summarize findings and actionable insights\n",
    "-----\n",
    "\n",
    "## 3.3 Tech Stack\n",
    "* **Data Preparation:** Python (Pandas/NumPy)\n",
    "* **Data Analysis:** SQL (MySQL)\n",
    "* **Visualization:** Power BI\n",
    "* **Version Control:** Git & GitHub\n",
    "\n",
    "---\n",
    "\n",
    "## 3.4 Deliverables\n",
    "\n",
    "### 1. Data Preparation & Modeling (Python)\n",
    "Located in the `/scripts` folder, the Python notebooks cover:\n",
    "* Initial data cleaning (handling missing values, outliers, and duplicates).\n",
    "* Data transformation and feature engineering.\n",
    "* Exporting the refined dataset for SQL integration.\n",
    "\n",
    "### 2. Data Analysis (SQL)\n",
    "The `/sql_queries` directory contains scripts that:\n",
    "* Model the data into a structured schema.\n",
    "* Simulate business transactions for deep-dive analysis.\n",
    "* Extract insights on **Customer Segmentation**, **Loyalty Trends**, and **Purchase Drivers**.\n",
    "\n",
    "### 3. Visualization & Insights (Power BI)\n",
    "The interactive dashboard includes:\n",
    "* KPI Overview (Total Revenue, Customer Count, Retention Rate).\n",
    "* Trend analysis over time.\n",
    "* Stakeholder-ready visuals for data-driven decision-making.\n",
    "\n",
    "### 4. Report & Presentation\n",
    "* **[Final Report](./docs/Final_Report.md):** A detailed summary of findings and business recommendations.\n",
    "* **[Presentation Deck](./docs/Presentation.pdf):** A visual summary designed for executive stakeholders.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d802e0b3",
   "metadata": {},
   "source": [
    "\n",
    "# 📂 **4. Repository Structure**\n",
    "```text\n",
    "├── data/               # Raw and cleaned datasets\n",
    "├── scripts/            # Python scripts & Jupyter Notebooks\n",
    "├── sql_queries/        # SQL files for analysis\n",
    "├── dashboard/          # Power BI file (.pbix)\n",
    "├── docs/               # Final report and presentation PDF\n",
    "└── README.md           # Project documentation"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
